// <auto-generated/>
using Microsoft.Extensions.Hosting;

namespace Projects;

/// <summary>
/// Project metadata for CarRentalService.Generator.Grpc.Host required by Aspire AppHost
/// </summary>
public class CarRentalService_Generator_Grpc_Host
{
    /// <summary>
    /// Configures the CarRentalService Generator for Aspire AppHost
    /// </summary>
    /// <param name="builder">Host application builder</param>
    /// <returns>Configured host application builder</returns>
    public static IHostApplicationBuilder AddCarRentalService_Generator_Grpc_Host(IHostApplicationBuilder builder)
    {
        return builder;
    }
}
